context:
  name: airflow-common
  version: "0.7.7"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-common/airflow_common-${{ version }}.tar.gz
  sha256: 847a12393af3603a45d4fc3d1c540cb61e2798a4f2b1e7b3a82f1b493177d915

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - airflow-pydantic >=1.4,<1.6
    - pydantic >=2

tests:
  - python:
      imports:
        - airflow_common
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Common Airflow Operators / Tasks
  homepage: https://github.com/airflow-laminar/airflow-common
  repository: https://github.com/airflow-laminar/airflow-common

extra:
  recipe-maintainers:
    - timkpaine
